---
name: save-hukamnama
on: [push, pull_request]

jobs:
  save-hukamnama:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get today's Hukamnama
        run: ./save.sh

      - name: Committing back to the repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions scheduled trigger"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin main
          git status
          git add .
          git commit -m "Adding Hukamnama for $(date '+%Y-%m-%d')"
          git push origin HEAD:main
